# Generated by Django 6.0.7 on 2026-09-24 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deneme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=160)),
                ('tarih', models.DateField()),
                ('kaynak_dosya', models.CharField(blank=True, max_length=255)),
                ('olusturulma', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Deneme',
                'verbose_name_plural': 'Denemeler',
                'ordering': ['-tarih', '-olusturulma'],
            },
        ),
        migrations.CreateModel(
            name='Ders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=160)),
                ('ad_key', models.CharField(max_length=160, unique=True)),
            ],
            options={
                'verbose_name': 'Ders',
                'verbose_name_plural': 'Dersler',
                'ordering': ['ad'],
            },
        ),
        migrations.CreateModel(
            name='Sinif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=32, unique=True)),
            ],
            options={
                'verbose_name': 'Sınıf',
                'verbose_name_plural': 'Sınıflar',
                'ordering': ['ad'],
            },
        ),
        migrations.CreateModel(
            name='Konu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=255)),
                ('ad_key', models.CharField(db_index=True, max_length=255)),
                ('ders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='konular', to='core.ders')),
            ],
            options={
                'verbose_name': 'Konu',
                'verbose_name_plural': 'Konular',
                'ordering': ['ders__ad', 'ad'],
            },
        ),
        migrations.CreateModel(
            name='Talebe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_soyad', models.CharField(max_length=160)),
                ('ad_soyad_key', models.CharField(db_index=True, max_length=160)),
                ('sinif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talebeler', to='core.sinif')),
            ],
            options={
                'verbose_name': 'Talebe',
                'verbose_name_plural': 'Talebeler',
                'ordering': ['ad_soyad'],
            },
        ),
        migrations.CreateModel(
            name='KonuSonuc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yuzde', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('net_dogru', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('net_toplam', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('deneme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sonuclar', to='core.deneme')),
                ('konu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sonuclar', to='core.konu')),
                ('talebe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sonuclar', to='core.talebe')),
            ],
            options={
                'verbose_name': 'Konu sonucu',
                'verbose_name_plural': 'Konu sonuçları',
            },
        ),
        migrations.AddConstraint(
            model_name='konu',
            constraint=models.UniqueConstraint(fields=('ders', 'ad_key'), name='uniq_konu_ders_ad'),
        ),
        migrations.AddConstraint(
            model_name='talebe',
            constraint=models.UniqueConstraint(fields=('sinif', 'ad_soyad_key'), name='uniq_talebe_sinif_ad'),
        ),
        migrations.AddConstraint(
            model_name='konusonuc',
            constraint=models.UniqueConstraint(fields=('deneme', 'talebe', 'konu'), name='uniq_sonuc_deneme_talebe_konu'),
        ),
    ]
