# Generated by Django 6.0.7 on 2026-09-24 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Etut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=160)),
                ('aktif', models.BooleanField(default=True)),
                ('olusturulma', models.DateTimeField(auto_now_add=True)),
                ('hoca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='etutler', to=settings.AUTH_USER_MODEL)),
                ('talebeler', models.ManyToManyField(blank=True, related_name='etutler', to='core.talebe')),
            ],
            options={
                'verbose_name': 'Etüt',
                'verbose_name_plural': 'Etütler',
                'ordering': ['ad'],
            },
        ),
    ]
